/* eslint-disable @typescript-eslint/restrict-template-expressions, @typescript-eslint/no-unnecessary-type-arguments, @typescript-eslint/no-unnecessary-type-conversion, @typescript-eslint/no-base-to-string, @typescript-eslint/no-unnecessary-condition */
import { createHash } from "node:crypto";
import { FieldValue, type DocumentData, type Firestore, type Query, type Timestamp, type Transaction } from "firebase-admin/firestore";
import type { Principal } from "../auth/authorization.js";
import { assertProjectTransition, type ProjectState } from "../projects/domain.js";
import { ConflictError, NotFoundError, BusinessRuleError } from "../shared/errors.js";
import { resolveChildContext, localDateIn, quarterAcceptsSubmissions, type ActiveQuarter } from "./context.js";
import type { CheckInInput } from "./schemas.js";

const id = (...parts: string[]) => createHash("sha256").update(parts.map((p) => `${p.length}:${p}`).join("|")).digest("base64url");
const iso = (value: unknown): string | null => value && typeof (value as Timestamp).toDate === "function" ? (value as Timestamp).toDate().toISOString() : null;
type ChildRecord = { id: string } & Record<string, unknown>;
const data = (doc: FirebaseFirestore.DocumentSnapshot): ChildRecord => ({ id: doc.id, ...(doc.data() ?? {}) });

export class ChildService {
  constructor(private readonly db: Firestore, private readonly clock = () => new Date()) {}
  private async scope(principal: Principal | undefined) { return resolveChildContext(this.db, principal, this.clock()); }
  private async list(query: Query<DocumentData>) { return (await query.get()).docs.map(data); }
  private requireWritable(quarter: ActiveQuarter | null): asserts quarter is ActiveQuarter {
    if (!quarter) throw new ConflictError("There is no active quarter.");
    if (!quarterAcceptsSubmissions(quarter)) throw new ConflictError("The active quarter is read-only.");
  }

  async today(principal: Principal | undefined) {
    const { context: c, participant, quarter } = await this.scope(principal); const localDate = localDateIn(this.clock(), c.timezone);
    const empty = { checkIn: { id: null, status: "not_started", completedAt: null }, gratitude: { required: false, completed: false }, character: { cycleId: null, selectedQualityCount: 0, requiredQualityCount: 0, completed: false }, bible: { activityId: null, title: null, activityType: null, completed: false }, reading: { assignmentId: null, title: null, completed: false }, project: { projectId: null, title: null, status: null, nextMilestone: null }, team: null, ownPoints: { quarterTotal: 0 } };
    if (!quarter) return { localDate, timezone: c.timezone, participant: { id: c.participantId, approvedDisplayName: String(participant.get("approvedDisplayName") ?? participant.get("displayName") ?? "") }, quarter: null, ...empty, updatedAt: this.clock().toISOString() };
    const [check, characterResult, bibleResult, readingResult, projects, own, team] = await Promise.all([
      this.db.doc(`dailyCheckins/${id(c.organizationId,c.participantId,quarter.id,localDate)}`).get(), this.character(principal), this.bible(principal), this.reading(principal), this.projects(principal),
      this.db.doc(`participantQuarterStats/${quarter.id}_${c.participantId}`).get(), c.teamId ? this.team(principal) : null,
    ]);
    const days = Math.max(1, Math.ceil((quarter.endsAt.toMillis()-quarter.startsAt.toMillis())/86400000)); const week = Math.min(Math.ceil(days/7), Math.max(1, Math.floor((this.clock().getTime()-quarter.startsAt.toMillis())/604800000)+1));
    const cp = check.exists ? check.data()! : {}; const character=characterResult as {cycle:ChildRecord|null;qualities:ChildRecord[];assessment:ChildRecord|null}; const bible=bibleResult as unknown as {activity:ChildRecord|null;response:ChildRecord|null}; const reading=readingResult as unknown as {assignment:ChildRecord|null;response:ChildRecord|null}; const characterResponses=Array.isArray(character.assessment?.responses)?character.assessment.responses:[];
    return { localDate, timezone: c.timezone, participant: { id: c.participantId, approvedDisplayName: String(participant.get("approvedDisplayName") ?? participant.get("displayName") ?? "") }, quarter: { id: quarter.id, name: quarter.name, weekNumber: week, totalWeeks: Math.ceil(days/7), status: quarter.status }, checkIn: { id: check.exists ? check.id : null, status: check.exists ? cp.status : "not_started", completedAt: iso(cp.completedAt) }, gratitude: { required: true, completed: Boolean(cp.gratitudeResponse && cp.status === "completed") }, character: { cycleId: character.cycle?.id ?? null, selectedQualityCount: characterResponses.length, requiredQualityCount: character.qualities.length, completed: character.assessment?.status === "completed" }, bible: bible.activity ? { activityId: bible.activity.id, title: bible.activity.title, activityType: bible.activity.activityType, completed: bible.response?.status === "completed" } : empty.bible, reading: reading.assignment ? { assignmentId: reading.assignment.id, title: reading.assignment.title, completed: reading.response?.status === "completed" } : empty.reading, project: projects[0] ? { projectId: projects[0].id, title: projects[0].title, status: projects[0].status, nextMilestone: projects[0].nextMilestone ?? null } : empty.project, team, ownPoints: { quarterTotal: Number(own.get("totalPoints") ?? 0) }, updatedAt: this.clock().toISOString() };
  }

  async getCheckIn(principal: Principal | undefined) { const { context:c, quarter }=await this.scope(principal); if(!quarter) return { available:false, reason:"no_active_quarter", checkIn:null }; const localDate=localDateIn(this.clock(),c.timezone); const snap=await this.db.doc(`dailyCheckins/${id(c.organizationId,c.participantId,quarter.id,localDate)}`).get(); return { available:true, localDate, timezone:c.timezone, checkIn:snap.exists?data(snap):null }; }
  async saveCheckIn(principal: Principal | undefined, input: CheckInInput, complete: boolean) { const {context:c,quarter}=await this.scope(principal); this.requireWritable(quarter); const localDate=localDateIn(this.clock(),c.timezone), ref=this.db.doc(`dailyCheckins/${id(c.organizationId,c.participantId,quarter.id,localDate)}`); const view=await this.character(principal); if(view.cycle) await this.validateCycle(c.organizationId,view.cycle,input.characterResponses,complete); else if(complete&&input.characterResponses.length) throw new ConflictError("No character cycle is available."); return this.db.runTransaction(async tx=>{ const old=await tx.get(ref); if(old.exists && ["completed","locked"].includes(String(old.get("status")))) return data(old); const record={organizationId:c.organizationId,participantId:c.participantId,quarterId:quarter.id,localDate,timezone:c.timezone,...input,status:complete?"completed":"draft",completedAt:complete?FieldValue.serverTimestamp():null,updatedAt:FieldValue.serverTimestamp(),version:Number(old.get("version")??0)+1,...(!old.exists?{createdAt:FieldValue.serverTimestamp()}: {})}; if(complete) await this.award(tx,c,quarter,"daily_checkin",ref.id); tx.set(ref,record,{merge:true}); return {id:ref.id,...record}; }); }
  private async validateCycle(org:string,cycle:ChildRecord,responses:CheckInInput["characterResponses"],complete:boolean){
    const qualityIds=Array.isArray(cycle.qualityIds)?cycle.qualityIds.filter((q):q is string=>typeof q==="string"):[], selected=new Set(qualityIds);
    if(qualityIds.length!==5||selected.size!==5)throw new ConflictError("The active character cycle must select exactly five unique qualities.");
    const qualities=await Promise.all(qualityIds.map(q=>this.db.doc(`characterQualities/${q}`).get()));
    if(qualities.some(q=>!q.exists||q.get("organizationId")!==org||q.get("status")!=="active"))throw new ConflictError("The active character cycle contains an unavailable quality.");
    const responseIds=responses.map(r=>r.qualityId);
    if(new Set(responseIds).size!==responseIds.length||responseIds.some(q=>!selected.has(q)))throw new BusinessRuleError("CHARACTER_ASSESSMENT_INVALID","Character responses must be unique qualities from the active cycle.");
    if(complete&&responses.length!==5)throw new BusinessRuleError("CHARACTER_ASSESSMENT_INCOMPLETE","Complete all five configured character reflections before submitting.");
  }

  async character(principal:Principal|undefined){ const {context:c,quarter}=await this.scope(principal); if(!quarter)return {available:false,reason:"no_active_quarter",cycle:null,qualities:[],assessment:null}; const cycles=await this.list(this.db.collection("characterCycles").where("organizationId","==",c.organizationId).where("participantId","==",c.participantId).where("quarterId","==",quarter.id).where("status","==","active").limit(2)); if(cycles.length>1)throw new ConflictError("Multiple active character cycles are configured."); if(!cycles[0])return {available:false,reason:"not_configured",cycle:null,qualities:[],assessment:null}; const qualityIds=Array.isArray(cycles[0].qualityIds)?cycles[0].qualityIds as string[]:[]; const qualities=(await Promise.all(qualityIds.map(q=>this.db.doc(`characterQualities/${q}`).get()))).filter(q=>q.exists&&q.get("organizationId")===c.organizationId&&q.get("status")==="active").map(data); if(qualityIds.length!==5||new Set(qualityIds).size!==5||qualities.length!==5)throw new ConflictError("The character cycle must contain exactly five unique active qualities."); const a=await this.db.doc(`characterAssessments/${id(quarter.id,String(cycles[0].id),c.participantId)}`).get(); return {available:true,cycle:cycles[0],qualities,assessment:a.exists?data(a):null}; }
  async saveCharacter(principal:Principal|undefined,responses:CheckInInput["characterResponses"],complete:boolean){const {context:c,quarter}=await this.scope(principal);this.requireWritable(quarter);const view=await this.character(principal);if(!view.cycle)throw new ConflictError("No character cycle is available.");await this.validateCycle(c.organizationId,view.cycle,responses,complete);const ref=this.db.doc(`characterAssessments/${id(quarter.id,String(view.cycle.id),c.participantId)}`);return this.db.runTransaction(async tx=>{const old=await tx.get(ref);if(old.exists&&["completed","locked"].includes(String(old.get("status"))))return data(old);const record={organizationId:c.organizationId,participantId:c.participantId,quarterId:quarter.id,cycleId:view.cycle.id,responses,status:complete?"completed":"draft",completedAt:complete?FieldValue.serverTimestamp():null,updatedAt:FieldValue.serverTimestamp(),version:Number(old.get("version")??0)+1,...(!old.exists?{createdAt:FieldValue.serverTimestamp()}:{})};if(complete)await this.award(tx,c,quarter,"character_assessment",ref.id);tx.set(ref,record,{merge:true});return{id:ref.id,...record};});}

  async bible(principal:Principal|undefined,specific?:string){return this.activityView(principal,"bible",specific)}
  async reading(principal:Principal|undefined,specific?:string){return this.activityView(principal,"reading",specific)}
  private async activityView(principal:Principal|undefined,kind:"bible"|"reading",specific?:string){const {context:c,quarter}=await this.scope(principal);if(!quarter)return {available:false,reason:"no_active_quarter",[kind==="bible"?"activity":"assignment"]:null,response:null};const collection=kind==="bible"?"bibleActivities":"readingAssignments";let docs:FirebaseFirestore.DocumentSnapshot[];if(specific){const d=await this.db.doc(`${collection}/${specific}`).get();if(!d.exists)throw new NotFoundError();docs=[d];}else docs=(await this.db.collection(collection).where("organizationId","==",c.organizationId).where("quarterId","==",quarter.id).where("status","==","active").limit(20).get()).docs;const now=this.clock().getTime();const chosen=docs.find(d=>d.get("organizationId")===c.organizationId&&d.get("quarterId")===quarter.id&&(!Array.isArray(d.get("participantIds"))||(d.get("participantIds") as string[]).includes(c.participantId))&&(!(d.get("availableFrom") as Timestamp|undefined)||(d.get("availableFrom") as Timestamp).toMillis()<=now)&&(!(d.get("availableUntil") as Timestamp|undefined)||(d.get("availableUntil") as Timestamp).toMillis()>=now));if(!chosen){if(specific)throw new NotFoundError();return {available:false,reason:"not_configured",[kind==="bible"?"activity":"assignment"]:null,response:null};}const responses=kind==="bible"?"bibleActivityResponses":"readingResponses",response=await this.db.doc(`${responses}/${id(quarter.id,chosen.id,c.participantId)}`).get();return {available:true,[kind==="bible"?"activity":"assignment"]:data(chosen),response:response.exists?data(response):null};}
  async respond(principal:Principal|undefined,kind:"bible"|"reading",resourceId:string,input:Record<string,unknown>){const {context:c,quarter}=await this.scope(principal);this.requireWritable(quarter);const view=await this.activityView(principal,kind,resourceId), resource=(view as Record<string,unknown>)[kind==="bible"?"activity":"assignment"] as Record<string,unknown>;const expected=kind==="bible"?resource.activityType:"reading_reflection";const response=input.response as Record<string,unknown>;if(response.type!==expected)throw new BusinessRuleError("RESPONSE_TYPE_MISMATCH","The response type does not match this activity.");const collection=kind==="bible"?"bibleActivityResponses":"readingResponses",ref=this.db.doc(`${collection}/${id(quarter.id,resourceId,c.participantId)}`),complete=input.status==="completed";return this.db.runTransaction(async tx=>{const old=await tx.get(ref);if(old.exists&&old.get("status")==="completed")return data(old);const record={organizationId:c.organizationId,participantId:c.participantId,quarterId:quarter.id,[kind==="bible"?"activityId":"assignmentId"]:resourceId,response,status:input.status,completedAt:complete?FieldValue.serverTimestamp():null,updatedAt:FieldValue.serverTimestamp(),...(!old.exists?{createdAt:FieldValue.serverTimestamp()}:{})};if(complete)await this.award(tx,c,quarter,kind==="bible"?"bible_activity":"reading",ref.id);tx.set(ref,record,{merge:true});return{id:ref.id,...record};});}

  async projects(principal:Principal|undefined){const {context:c}=await this.scope(principal);return this.list(this.db.collection("projects").where("organizationId","==",c.organizationId).where("participantId","==",c.participantId).limit(100));}
  async project(principal:Principal|undefined,projectId:string){const {context:c}=await this.scope(principal),snap=await this.db.doc(`projects/${projectId}`).get();if(!snap.exists||snap.get("organizationId")!==c.organizationId||snap.get("participantId")!==c.participantId)throw new NotFoundError();const [milestones,updates]=await Promise.all([this.list(this.db.collection("projectMilestones").where("projectId","==",projectId)),this.list(this.db.collection("projectUpdates").where("projectId","==",projectId))]);return{project:data(snap),milestones,updates};}
  async createProject(principal:Principal|undefined,input:Record<string,unknown>){const {context:c,quarter}=await this.scope(principal);this.requireWritable(quarter);const ref=this.db.collection("projects").doc();const record={...input,organizationId:c.organizationId,participantId:c.participantId,quarterId:quarter?.id??null,status:"idea",version:1,createdAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()};await ref.create(record);return{data:data(await ref.get()),created:true};}
  async patchProject(principal:Principal|undefined,projectId:string,input:Record<string,unknown>){const {context:c}=await this.scope(principal);await this.project(principal,projectId);const ref=this.db.doc(`projects/${projectId}`);return this.db.runTransaction(async tx=>{const old=await tx.get(ref),version=Number(input.version);if(old.get("version")!==version)throw new ConflictError("Project version is stale.");const oldStatus=String(old.get("status")) as ProjectState,newStatus=input.status?String(input.status):oldStatus;if(newStatus!==oldStatus)assertProjectTransition(oldStatus,newStatus==="completion"?"completed":newStatus as ProjectState);const patch={...input,status:newStatus==="completion"?"completed":newStatus,version:version+1,updatedAt:FieldValue.serverTimestamp()};tx.update(ref,patch);if(newStatus!==oldStatus)tx.create(this.db.collection("auditLogs").doc(),{event:"PROJECT_TRANSITION",organizationId:old.get("organizationId"),participantId:old.get("participantId"),projectId,from:oldStatus,to:patch.status,actorId:c.actorUid,createdAt:FieldValue.serverTimestamp()});return{id:projectId,...old.data(),...patch};});}
  async addMilestone(principal:Principal|undefined,projectId:string,input:Record<string,unknown>){const {context:c,quarter}=await this.scope(principal);this.requireWritable(quarter);await this.project(principal,projectId);const ref=this.db.collection("projectMilestones").doc(),record={...input,projectId,organizationId:c.organizationId,participantId:c.participantId,status:"pending",createdAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()};await ref.create(record);return{data:data(await ref.get()),created:true};}
  async addUpdate(principal:Principal|undefined,projectId:string,input:Record<string,unknown>){const {context:c,quarter}=await this.scope(principal);this.requireWritable(quarter);await this.project(principal,projectId);const ref=this.db.collection("projectUpdates").doc(),milestoneId=input.milestoneId as string|undefined;await this.db.runTransaction(async tx=>{if(milestoneId){const mref=this.db.doc(`projectMilestones/${milestoneId}`),m=await tx.get(mref);if(!m.exists||m.get("projectId")!==projectId||m.get("participantId")!==c.participantId)throw new NotFoundError();if(input.completeMilestone&&m.get("status")!=="completed"){if(quarter)await this.award(tx,c,quarter,"project_milestone",mref.id);tx.update(mref,{status:"completed",completedAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()});}}const record={text:input.text,projectId,organizationId:c.organizationId,participantId:c.participantId,createdAt:FieldValue.serverTimestamp()};tx.create(ref,record);});return{data:data(await ref.get()),created:true};}

  async team(principal:Principal|undefined){const {context:c,quarter}=await this.scope(principal);if(!quarter||!c.teamId)return null;const membership=await this.db.collection("teamMembers").where("participantId","==",c.participantId).where("status","==","active").get();if(!membership.docs.some(m=>m.get("teamId")===c.teamId&&m.get("organizationId")===c.organizationId))return null;const [team,stats,own]=await Promise.all([this.db.doc(`teams/${c.teamId}`).get(),this.db.doc(`teamQuarterStats/${quarter.id}_${c.teamId}`).get(),this.db.doc(`participantQuarterStats/${quarter.id}_${c.participantId}`).get()]);if(!team.exists||team.get("organizationId")!==c.organizationId)return null;const total=Number(stats.get("totalPoints")??0),target=Number(quarter.targetPoints??0);return{id:c.teamId,displayName:String(team.get("approvedDisplayName")??team.get("displayName")??""),quarter:{id:quarter.id,name:quarter.name,status:quarter.status},quarterPoints:total,targetPoints:target,progressPercentage:target>0?Math.min(100,Math.round(total/target*100)):0,ownContribution:Number(own.get("totalPoints")??0),calculatedAt:iso(stats.get("updatedAt"))??this.clock().toISOString()};}
  async gratitude(principal: Principal | undefined, cursor?: string) {
    const { context: c } = await this.scope(principal);
    let query: Query<DocumentData> = this.db.collection("gratitudeEntries").where("organizationId", "==", c.organizationId).where("participantId", "==", c.participantId).orderBy("localDate", "desc").limit(21);
    if (cursor) { const after = await this.db.doc(`gratitudeEntries/${cursor}`).get(); if (!after.exists || after.get("organizationId") !== c.organizationId || after.get("participantId") !== c.participantId) throw new NotFoundError(); query = query.startAfter(after); }
    const docs = (await query.get()).docs, shown = docs.slice(0, 20);
    return { items: shown.map(data), nextCursor: docs.length > 20 ? shown.at(-1)?.id ?? null : null };
  }

  async saveGratitude(principal: Principal | undefined, text: string) {
    const { context: c, quarter } = await this.scope(principal); this.requireWritable(quarter);
    const localDate = localDateIn(this.clock(), c.timezone), ref = this.db.doc(`gratitudeEntries/${id(c.organizationId, c.participantId, localDate)}`), old = await ref.get();
    if (old.exists) return { data: data(old), created: false };
    await ref.create({ organizationId: c.organizationId, participantId: c.participantId, quarterId: quarter.id, localDate, text, createdAt: FieldValue.serverTimestamp() });
    return { data: data(await ref.get()), created: true };
  }

  private async assignedDefinitions(principal: Principal | undefined, collection: string) {
    const { context: c, quarter } = await this.scope(principal); if (!quarter) return [];
    const records = await this.list(this.db.collection(collection).where("organizationId", "==", c.organizationId).where("quarterId", "==", quarter.id).where("status", "==", "active").limit(100));
    return records.filter((record) => !Array.isArray(record.participantIds) || record.participantIds.includes(c.participantId));
  }
  async specialActivities(principal: Principal | undefined) { return this.assignedDefinitions(principal, "specialActivities"); }
  async surveys(principal: Principal | undefined) { return this.assignedDefinitions(principal, "surveys"); }

  async completeSpecialActivity(principal: Principal | undefined, activityId: string, input: Record<string, unknown>) {
    const { context: c, quarter } = await this.scope(principal); this.requireWritable(quarter);
    if (!(await this.assignedDefinitions(principal, "specialActivities")).some((item) => item.id === activityId)) throw new NotFoundError();
    const ref = this.db.doc(`specialActivitySubmissions/${id(quarter.id, activityId, c.participantId)}`);
    return this.db.runTransaction(async (tx) => { const old = await tx.get(ref); if (old.exists) return { data: data(old), created: false }; const record = { organizationId: c.organizationId, participantId: c.participantId, quarterId: quarter.id, activityId, response: input.response ?? null, status: "completed", completedAt: FieldValue.serverTimestamp() }; await this.award(tx, c, quarter, "special_activity", ref.id); tx.create(ref, record); return { data: { id: ref.id, ...record }, created: true }; });
  }

  async submitSurvey(principal: Principal | undefined, surveyId: string, input: Record<string, unknown>) {
    const { context: c, quarter } = await this.scope(principal); this.requireWritable(quarter);
    const survey = (await this.assignedDefinitions(principal, "surveys")).find((item) => item.id === surveyId); if (!survey) throw new NotFoundError();
    const questionIds = new Set((Array.isArray(survey.questions) ? survey.questions : []).map((question) => (question as Record<string, unknown>).id)); const answers = input.answers as Array<Record<string, unknown>>;
    if (answers.some((answer) => !questionIds.has(answer.questionId))) throw new BusinessRuleError("SURVEY_ANSWER_INVALID", "An answer references an unavailable question.");
    const ref = this.db.doc(`surveySubmissions/${id(quarter.id, surveyId, c.participantId)}`), complete = input.status === "completed";
    return this.db.runTransaction(async (tx) => { const old = await tx.get(ref); if (old.exists && old.get("status") === "completed") return data(old); const record = { organizationId: c.organizationId, participantId: c.participantId, quarterId: quarter.id, surveyId, answers, status: input.status, updatedAt: FieldValue.serverTimestamp(), completedAt: complete ? FieldValue.serverTimestamp() : null }; if (complete) await this.award(tx, c, quarter, "survey", ref.id); tx.set(ref, record, { merge: true }); return { id: ref.id, ...record }; });
  }

  async points(principal: Principal | undefined, cursor?: string) {
    const { context: c } = await this.scope(principal); let query: Query<DocumentData> = this.db.collection("pointLedger").where("participantId", "==", c.participantId).orderBy("createdAt", "desc").limit(21);
    if (cursor) { const after = await this.db.doc(`pointLedger/${cursor}`).get(); if (!after.exists || after.get("organizationId") !== c.organizationId || after.get("participantId") !== c.participantId) throw new NotFoundError(); query = query.startAfter(after); }
    const docs = (await query.get()).docs.filter((doc) => doc.get("organizationId") === c.organizationId), shown = docs.slice(0, 20); return { items: shown.map(data), nextCursor: docs.length > 20 ? shown.at(-1)?.id ?? null : null, calculatedAt: this.clock().toISOString() };
  }
  async awards(principal: Principal | undefined) { const { context: c } = await this.scope(principal); return this.list(this.db.collection("awards").where("organizationId", "==", c.organizationId).where("participantId", "==", c.participantId).limit(100)); }

  private async award(tx:Transaction,c:{organizationId:string;participantId:string;teamId:string|null;actorUid:string},quarter:ActiveQuarter,sourceType:string,sourceId:string){const rules=await tx.get(this.db.collection("pointRules").where("organizationId","==",c.organizationId).where("sourceType","==",sourceType).where("status","==","active"));const now=this.clock().getTime(),eligible=rules.docs.filter(r=>(!r.get("quarterId")||r.get("quarterId")===quarter.id)&&(!(r.get("effectiveFrom") as Timestamp|undefined)||(r.get("effectiveFrom") as Timestamp).toMillis()<=now)&&(!(r.get("effectiveUntil") as Timestamp|undefined)||(r.get("effectiveUntil") as Timestamp).toMillis()>=now));if(eligible.length>1)throw new ConflictError("Multiple eligible point rules are configured.");if(!eligible[0])return;const rule=eligible[0],points=Number(rule.get("points"));if(!Number.isSafeInteger(points)||points<=0)throw new ConflictError("The point rule is invalid.");const ledger=this.db.doc(`pointLedger/${id(quarter.id,sourceType,sourceId,c.participantId)}`),old=await tx.get(ledger);if(old.exists)return;tx.create(ledger,{ruleId:rule.id,ruleVersion:Number(rule.get("version")??1),ruleSnapshot:{sourceType,points},points,sourceType,sourceId,organizationId:c.organizationId,quarterId:quarter.id,participantId:c.participantId,teamId:c.teamId,actorId:c.actorUid,createdAt:FieldValue.serverTimestamp()});if(points>0){tx.set(this.db.doc(`participantQuarterStats/${quarter.id}_${c.participantId}`),{organizationId:c.organizationId,participantId:c.participantId,quarterId:quarter.id,totalPoints:FieldValue.increment(points),updatedAt:FieldValue.serverTimestamp()},{merge:true});if(c.teamId)tx.set(this.db.doc(`teamQuarterStats/${quarter.id}_${c.teamId}`),{organizationId:c.organizationId,teamId:c.teamId,quarterId:quarter.id,totalPoints:FieldValue.increment(points),updatedAt:FieldValue.serverTimestamp()},{merge:true});}}
}
