import { Router, type Request, type RequestHandler } from "express";
import { z } from "zod";
import { db } from "../../config/firebase.js";
import { requireRole } from "../../middleware/authorize.js";
import { validateBody } from "../../middleware/validate.js";
import { ChildService } from "../service.js";
import { activityResponseSchema, characterAssessmentSchema, checkInSchema, gratitudeSchema, milestoneSchema, projectCreateSchema, projectPatchSchema, specialActivitySubmissionSchema, surveySubmissionSchema, updateSchema } from "../schemas.js";

const router=Router(), service=new ChildService(db), resourceId=z.string().min(1).max(128).regex(/^[A-Za-z0-9_-]+$/);
router.use(requireRole("child"));
interface CreateResult<T> { data:T; created:boolean }
const handle=(fn:(req:Request)=>Promise<unknown>):RequestHandler=>async(req,res,next)=>{try{res.status(200).json({data:await fn(req)});}catch(e){next(e);}};
const create=(fn:(req:Request)=>Promise<CreateResult<unknown>>):RequestHandler=>async(req,res,next)=>{try{const result=await fn(req);res.status(result.created?201:200).json({data:result.data});}catch(e){next(e);}};
const pid=(req:Request)=>resourceId.parse(req.params.projectId), aid=(req:Request)=>resourceId.parse(req.params.activityId), rid=(req:Request)=>resourceId.parse(req.params.assignmentId);

router.get("/today",handle(req=>service.today(req.principal)));
router.get("/check-ins/today",handle(req=>service.getCheckIn(req.principal)));
router.put("/check-ins/today/draft",validateBody(checkInSchema),handle(req=>service.saveCheckIn(req.principal,req.body,false)));
router.post("/check-ins/today/complete",validateBody(checkInSchema),handle(req=>service.saveCheckIn(req.principal,req.body,true)));
router.get("/gratitude",handle(req=>service.gratitude(req.principal,typeof req.query.cursor==="string"?req.query.cursor:undefined)));
router.post("/gratitude",validateBody(gratitudeSchema),create(req=>service.saveGratitude(req.principal,req.body.text)));
router.get("/character",handle(req=>service.character(req.principal)));
router.put("/character/draft",validateBody(characterAssessmentSchema),handle(req=>service.saveCharacter(req.principal,req.body.responses,false)));
router.post("/character/complete",validateBody(characterAssessmentSchema),handle(req=>service.saveCharacter(req.principal,req.body.responses,true)));
router.get("/bible",handle(req=>service.bible(req.principal)));
router.get("/bible/:activityId",handle(req=>service.bible(req.principal,aid(req))));
router.post("/bible/:activityId/responses",validateBody(activityResponseSchema),handle(req=>service.respond(req.principal,"bible",aid(req),req.body)));
router.get("/reading",handle(req=>service.reading(req.principal)));
router.get("/reading/:assignmentId",handle(req=>service.reading(req.principal,rid(req))));
router.post("/reading/:assignmentId/responses",validateBody(activityResponseSchema),handle(req=>service.respond(req.principal,"reading",rid(req),req.body)));
router.get("/projects",handle(req=>service.projects(req.principal)));
router.post("/projects",validateBody(projectCreateSchema),create(req=>service.createProject(req.principal,req.body)));
router.get("/projects/:projectId",handle(req=>service.project(req.principal,pid(req))));
router.patch("/projects/:projectId",validateBody(projectPatchSchema),handle(req=>service.patchProject(req.principal,pid(req),req.body)));
router.post("/projects/:projectId/milestones",validateBody(milestoneSchema),create(req=>service.addMilestone(req.principal,pid(req),req.body)));
router.post("/projects/:projectId/updates",validateBody(updateSchema),create(req=>service.addUpdate(req.principal,pid(req),req.body)));
router.get("/team",handle(req=>service.team(req.principal)));
router.get("/special-activities",handle(req=>service.specialActivities(req.principal)));
router.post("/special-activities/:activityId/submissions",validateBody(specialActivitySubmissionSchema),create(req=>service.completeSpecialActivity(req.principal,aid(req),req.body)));
router.get("/surveys",handle(req=>service.surveys(req.principal)));
router.post("/surveys/:activityId/submissions",validateBody(surveySubmissionSchema),handle(req=>service.submitSurvey(req.principal,aid(req),req.body)));
router.get("/points",handle(req=>service.points(req.principal,typeof req.query.cursor==="string"?req.query.cursor:undefined)));
router.get("/awards",handle(req=>service.awards(req.principal)));
export default router;
